#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later

# export LANG=C
PRJ_ROOT="$(dirname "${BASH_SOURCE[0]}")"
PRJ_ROOT="$(cd "${PRJ_ROOT}" && pwd -P)"
# shellcheck source=scripts/main.sh
source "${PRJ_ROOT}/scripts/main.sh"

# shellcheck source=./lib_py.sh
. /dev/null
sh.lib.import py

# shellcheck source=./lib_dist.sh
. /dev/null
sh.lib.import dist

# commands needed for the developer environment
PRJ_DEV_REQUIREMENTS=(bash git shfmt)
# packages that provide these commands
PRJ_DEV_PACKAGES=(
    "${DIST_DEV_PACKAGES[@]}"
    shfmt
)

MAIN_CMD_LIST=(
    "prepare"
    "env: env.build env.drop"
    "cmd"
    "test: test.bin test.suites"
    "shell"
)

# prepare
# -------

prepare.help() {
    $FMT <<EOF
install tools required by ${MAIN} (sudo)

usage:
  ${MAIN} ${MAIN_CMD}

To install packages from ${DIST_ID}'s package manager, super user privileges are
needed (sudo/su).
EOF
    dist.pkg.show "${PRJ_DEV_PACKAGES[@]}"
}

prepare() {
  TITLE="Install tools required by ${MAIN}" dist.pkg.install "${PRJ_DEV_PACKAGES[@]}"

}

# env
# ---

env.build.help()  { echo "build project's developer environment"; }
env.build() {
    scripts.requires "${PRJ_DEV_REQUIREMENTS[@]}" \
        || sh.die.err $? "first install missing requirements, use '${MAIN} prepare --help' for more info"

    py.env.build
    # https://setuptools.pypa.io/en/latest/userguide/development_mode.html
    "${PY_VENV}/bin/pip" install -e ".[dev,test]"
    env.build.post
}

env.build.post() {
    env.source
}

env.drop.help()  { echo "remove artifacts from the local developer environment"; }
env.drop()  {
    py.env.drop
}

env.source() {
    py.env.activate
    echo "" > /dev/null
}


# cmd
# ---

cmd.help() { echo "run command in project's environment"; }
cmd() {
    (   set -e
	# FIXME ..
	# env.source
        "$@"
    )
    sh.prompt-err $?
}

clean.help() { echo "clean up project folders"; }
clean() {
    (   set -e
	msg.build CLEAN "clean up project folder"
	py.clean
    )
    sh.prompt-err $?
}

# test
# ----

test.help() {
    $FMT <<EOF
run project's test needed to pass quality gate

To run really all tests, better use::

  make test

which will call this test procedure also.
EOF
}

test() {
    (   set -e
	test.suites
	test.bin
	test.etc

	msg.build TEST "shellcheck ./prj"
	shellcheck -x -s bash ./prj
	# msg.build TEST "pylint ./src"
	# cmd pylint ./src

    )
    sh.prompt-err $?
}


test.bin.help() { echo "run tests (shellcheck) on ./bin/*"; }
test.bin() {
    (   set -e
	msg.build TEST "shellcheck scripts in ./bin/*"
	pushd ./bin &> /dev/null
	shellcheck -x -s bash ./*
	popd &> /dev/null
    )
    sh.prompt-err $?
}


test.etc.help() { echo "run tests (shellcheck) on ./etc/*.env"; }
test.etc() {
    (   set -e
	msg.build TEST "shellcheck scripts in ./etc/*.env"
	pushd ./etc &> /dev/null
	shellcheck -e SC2034 -x -s bash ./*.env
	popd &> /dev/null
    )
    sh.prompt-err $?
}


test.suites.help() { echo "run tests (shellcheck) on ./scripts/*"; }
test.suites() {
    (   set -e
	msg.build TEST "shellcheck scripts in ./suites/"
	shellcheck -x -s bash ./suites/*/*.env ./suites/*/*.sh
    )
    sh.prompt-err $?
}

# shell
# -----

shell.help() { echo "start a shell in project's environment"; }
shell() {
    (   set -e
	env.source
        bash --rcfile <(
	    cat "${PY_VENV}/bin/.pysandbox-complete.bash";
	)
    )
    sh.prompt-err $?
}


main "$@"
